// Galactica is a Layer 1 protocol with zero-knowledge and privacy features.
// Copyright (C) 2025 Galactica Network
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: galactica/inflation/query.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae5baee6426d48ab, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae5baee6426d48ab, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryCurrentEpochDistributionRequest is request type for
// Query/CurrentEpochDistribution RPC method.
type QueryCurrentEpochDistributionRequest struct {
}

func (m *QueryCurrentEpochDistributionRequest) Reset()         { *m = QueryCurrentEpochDistributionRequest{} }
func (m *QueryCurrentEpochDistributionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCurrentEpochDistributionRequest) ProtoMessage()    {}
func (*QueryCurrentEpochDistributionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae5baee6426d48ab, []int{2}
}
func (m *QueryCurrentEpochDistributionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCurrentEpochDistributionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCurrentEpochDistributionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCurrentEpochDistributionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCurrentEpochDistributionRequest.Merge(m, src)
}
func (m *QueryCurrentEpochDistributionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCurrentEpochDistributionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCurrentEpochDistributionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCurrentEpochDistributionRequest proto.InternalMessageInfo

// QueryCurrentEpochDistributionResponse is response type for
// Query/CurrentEpochDistribution RPC method.
type QueryCurrentEpochDistributionResponse struct {
	// Distribution of minted tokens for the current epoch.
	Distribution CurrentEpochInflationDistribution `protobuf:"bytes,1,opt,name=distribution,proto3" json:"distribution"`
	// Duration of one epoch.
	EpochDuration time.Duration `protobuf:"bytes,2,opt,name=epoch_duration,json=epochDuration,proto3,stdduration" json:"epoch_duration,omitempty" yaml:"epoch_duration"`
}

func (m *QueryCurrentEpochDistributionResponse) Reset()         { *m = QueryCurrentEpochDistributionResponse{} }
func (m *QueryCurrentEpochDistributionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCurrentEpochDistributionResponse) ProtoMessage()    {}
func (*QueryCurrentEpochDistributionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae5baee6426d48ab, []int{3}
}
func (m *QueryCurrentEpochDistributionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCurrentEpochDistributionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCurrentEpochDistributionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCurrentEpochDistributionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCurrentEpochDistributionResponse.Merge(m, src)
}
func (m *QueryCurrentEpochDistributionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCurrentEpochDistributionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCurrentEpochDistributionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCurrentEpochDistributionResponse proto.InternalMessageInfo

func (m *QueryCurrentEpochDistributionResponse) GetDistribution() CurrentEpochInflationDistribution {
	if m != nil {
		return m.Distribution
	}
	return CurrentEpochInflationDistribution{}
}

func (m *QueryCurrentEpochDistributionResponse) GetEpochDuration() time.Duration {
	if m != nil {
		return m.EpochDuration
	}
	return 0
}

// CurrentEpochInflationDistribution is a distribution of inflation for the
// current epoch.
type CurrentEpochInflationDistribution struct {
	// Amount of coins to be distributed to the validators.
	ValidatorsShare types.Coin `protobuf:"bytes,1,opt,name=validators_share,json=validatorsShare,proto3" json:"validators_share"`
	// Distribution of shares for other roles. Role name is used as a key.
	OtherShares map[string]CurrentEpochInflationShare `protobuf:"bytes,2,rep,name=other_shares,json=otherShares,proto3" json:"other_shares" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *CurrentEpochInflationDistribution) Reset()         { *m = CurrentEpochInflationDistribution{} }
func (m *CurrentEpochInflationDistribution) String() string { return proto.CompactTextString(m) }
func (*CurrentEpochInflationDistribution) ProtoMessage()    {}
func (*CurrentEpochInflationDistribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae5baee6426d48ab, []int{4}
}
func (m *CurrentEpochInflationDistribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CurrentEpochInflationDistribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CurrentEpochInflationDistribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CurrentEpochInflationDistribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentEpochInflationDistribution.Merge(m, src)
}
func (m *CurrentEpochInflationDistribution) XXX_Size() int {
	return m.Size()
}
func (m *CurrentEpochInflationDistribution) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentEpochInflationDistribution.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentEpochInflationDistribution proto.InternalMessageInfo

func (m *CurrentEpochInflationDistribution) GetValidatorsShare() types.Coin {
	if m != nil {
		return m.ValidatorsShare
	}
	return types.Coin{}
}

func (m *CurrentEpochInflationDistribution) GetOtherShares() map[string]CurrentEpochInflationShare {
	if m != nil {
		return m.OtherShares
	}
	return nil
}

// CurrentEpochInflationShare defines amount of tokens to be distributed in the
// current epoch for various roles other than validators.
type CurrentEpochInflationShare struct {
	// Address to which the inflation share would be distributed.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Name is an identifier of a role that would receive the inflation share.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Share is an amount of coin to be distributed to this role.
	Share types.Coin `protobuf:"bytes,3,opt,name=share,proto3" json:"share"`
}

func (m *CurrentEpochInflationShare) Reset()         { *m = CurrentEpochInflationShare{} }
func (m *CurrentEpochInflationShare) String() string { return proto.CompactTextString(m) }
func (*CurrentEpochInflationShare) ProtoMessage()    {}
func (*CurrentEpochInflationShare) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae5baee6426d48ab, []int{5}
}
func (m *CurrentEpochInflationShare) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CurrentEpochInflationShare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CurrentEpochInflationShare.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CurrentEpochInflationShare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentEpochInflationShare.Merge(m, src)
}
func (m *CurrentEpochInflationShare) XXX_Size() int {
	return m.Size()
}
func (m *CurrentEpochInflationShare) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentEpochInflationShare.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentEpochInflationShare proto.InternalMessageInfo

func (m *CurrentEpochInflationShare) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CurrentEpochInflationShare) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CurrentEpochInflationShare) GetShare() types.Coin {
	if m != nil {
		return m.Share
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "galactica.inflation.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "galactica.inflation.QueryParamsResponse")
	proto.RegisterType((*QueryCurrentEpochDistributionRequest)(nil), "galactica.inflation.QueryCurrentEpochDistributionRequest")
	proto.RegisterType((*QueryCurrentEpochDistributionResponse)(nil), "galactica.inflation.QueryCurrentEpochDistributionResponse")
	proto.RegisterType((*CurrentEpochInflationDistribution)(nil), "galactica.inflation.CurrentEpochInflationDistribution")
	proto.RegisterMapType((map[string]CurrentEpochInflationShare)(nil), "galactica.inflation.CurrentEpochInflationDistribution.OtherSharesEntry")
	proto.RegisterType((*CurrentEpochInflationShare)(nil), "galactica.inflation.CurrentEpochInflationShare")
}

func init() { proto.RegisterFile("galactica/inflation/query.proto", fileDescriptor_ae5baee6426d48ab) }

var fileDescriptor_ae5baee6426d48ab = []byte{
	// 678 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcf, 0x4f, 0xd4, 0x40,
	0x18, 0xdd, 0x96, 0x1f, 0x86, 0x01, 0x15, 0x07, 0x4c, 0x96, 0xd5, 0x74, 0xb1, 0xf1, 0x07, 0x21,
	0xd0, 0x86, 0x35, 0x18, 0x25, 0x91, 0x98, 0x05, 0x24, 0x7a, 0x41, 0x6b, 0xbc, 0x78, 0xc1, 0xd9,
	0xee, 0xd0, 0x9d, 0xb8, 0xed, 0x94, 0x99, 0x29, 0x71, 0x4f, 0x46, 0x8f, 0x5e, 0x34, 0xf1, 0xe2,
	0x9f, 0xe0, 0xd1, 0x3f, 0x83, 0x23, 0xd1, 0x8b, 0x5e, 0xd0, 0x80, 0x89, 0x89, 0x47, 0x13, 0xef,
	0xa6, 0x33, 0x53, 0xe8, 0xea, 0x6e, 0x76, 0xc3, 0x65, 0x33, 0xfd, 0xfa, 0xde, 0xfb, 0xde, 0xf7,
	0x76, 0xbe, 0x82, 0x72, 0x80, 0x9a, 0xc8, 0x17, 0xc4, 0x47, 0x2e, 0x89, 0xb6, 0x9a, 0x48, 0x10,
	0x1a, 0xb9, 0xdb, 0x09, 0x66, 0x2d, 0x27, 0x66, 0x54, 0x50, 0x38, 0x71, 0x04, 0x70, 0x8e, 0x00,
	0xa5, 0x73, 0x28, 0x24, 0x11, 0x75, 0xe5, 0xaf, 0xc2, 0x95, 0x66, 0x7d, 0xca, 0x43, 0xca, 0xdd,
	0x1a, 0xe2, 0x58, 0x09, 0xb8, 0x3b, 0x0b, 0x35, 0x2c, 0xd0, 0x82, 0x1b, 0xa3, 0x80, 0x44, 0x92,
	0xa8, 0xb1, 0x56, 0x1e, 0x9b, 0xa1, 0x7c, 0x4a, 0xb2, 0xf7, 0x93, 0x01, 0x0d, 0xa8, 0x3c, 0xba,
	0xe9, 0x49, 0x57, 0x2f, 0x06, 0x94, 0x06, 0x4d, 0xec, 0xa2, 0x98, 0xb8, 0x28, 0x8a, 0xa8, 0x90,
	0x92, 0x3c, 0xd3, 0xd4, 0x6f, 0xe5, 0x53, 0x2d, 0xd9, 0x72, 0xeb, 0x09, 0xcb, 0xf7, 0x9c, 0xee,
	0x34, 0x68, 0x8c, 0x18, 0x0a, 0xb5, 0x82, 0x3d, 0x09, 0xe0, 0xc3, 0xd4, 0xf7, 0x03, 0x59, 0xf4,
	0xf0, 0x76, 0x82, 0xb9, 0xb0, 0x1f, 0x83, 0x89, 0xb6, 0x2a, 0x8f, 0x69, 0xc4, 0x31, 0x5c, 0x06,
	0xc3, 0x8a, 0x5c, 0x34, 0xa6, 0x8d, 0x99, 0xd1, 0xca, 0x05, 0xa7, 0x43, 0x4e, 0x8e, 0x22, 0x55,
	0x47, 0x76, 0xf7, 0xcb, 0x85, 0x0f, 0x3f, 0x3f, 0xce, 0x1a, 0x9e, 0x66, 0xd9, 0x57, 0xc1, 0x65,
	0x29, 0xbb, 0x92, 0x30, 0x86, 0x23, 0xb1, 0x16, 0x53, 0xbf, 0xb1, 0x4a, 0xb8, 0x60, 0xa4, 0x96,
	0xa4, 0xd4, 0xac, 0xfd, 0x6b, 0x13, 0x5c, 0xe9, 0x01, 0xd4, 0x8e, 0x9e, 0x82, 0xb1, 0x7a, 0xae,
	0xae, 0x7d, 0xdd, 0xe8, 0xe8, 0x2b, 0x2f, 0x76, 0x2f, 0xab, 0xe6, 0x55, 0xab, 0x83, 0xa9, 0x65,
	0xaf, 0x4d, 0x11, 0xbe, 0x00, 0x67, 0x70, 0xca, 0xd8, 0xcc, 0xa2, 0x2d, 0x9a, 0xb2, 0xc7, 0x94,
	0xa3, 0xb2, 0x77, 0xb2, 0xec, 0x9d, 0x55, 0x0d, 0xa8, 0xde, 0x4e, 0x65, 0x7e, 0xed, 0x97, 0x8b,
	0xed, 0xc4, 0x39, 0x1a, 0x12, 0x81, 0xc3, 0x58, 0xb4, 0x7e, 0xef, 0x97, 0xcf, 0xb7, 0x50, 0xd8,
	0x5c, 0xb2, 0xdb, 0x11, 0xf6, 0xfb, 0x6f, 0x65, 0xc3, 0x3b, 0x2d, 0x8b, 0x99, 0x9a, 0xfd, 0xc9,
	0x04, 0x97, 0x7a, 0x5a, 0x87, 0xf7, 0xc1, 0xf8, 0x0e, 0x6a, 0x92, 0x3a, 0x12, 0x94, 0xf1, 0x4d,
	0xde, 0x40, 0x0c, 0xeb, 0x30, 0xa6, 0x1c, 0x75, 0xf1, 0x9c, 0xf4, 0xe2, 0x39, 0xfa, 0xe2, 0x39,
	0x2b, 0x94, 0x64, 0xf3, 0x9e, 0x3d, 0x26, 0x3e, 0x4a, 0x79, 0x30, 0x06, 0x63, 0x54, 0x34, 0x30,
	0x53, 0x32, 0xbc, 0x68, 0x4e, 0x0f, 0xcc, 0x8c, 0x56, 0xd6, 0x4f, 0x16, 0xaa, 0xb3, 0x91, 0x4a,
	0x49, 0x61, 0xbe, 0x16, 0x09, 0xd6, 0xd2, 0x5d, 0x47, 0xe9, 0x71, 0xbd, 0x44, 0xc1, 0xf8, 0xbf,
	0x30, 0x38, 0x0e, 0x06, 0x9e, 0xe1, 0x96, 0x1c, 0x62, 0xc4, 0x4b, 0x8f, 0x70, 0x0d, 0x0c, 0xed,
	0xa0, 0x66, 0x82, 0xf5, 0x3f, 0xe0, 0xf6, 0x6f, 0x48, 0xea, 0x7a, 0x8a, 0xbd, 0x64, 0xde, 0x34,
	0xec, 0x97, 0x06, 0x28, 0x75, 0x47, 0xc2, 0x22, 0x38, 0x85, 0xea, 0x75, 0x86, 0x39, 0xd7, 0xfd,
	0xb3, 0x47, 0x08, 0xc1, 0x60, 0x84, 0x42, 0x65, 0x61, 0xc4, 0x93, 0x67, 0xb8, 0x08, 0x86, 0x54,
	0xe0, 0x03, 0xfd, 0x05, 0xae, 0xd0, 0x95, 0x3f, 0x26, 0x18, 0x92, 0xb7, 0x1c, 0xbe, 0x31, 0xc0,
	0xb0, 0xda, 0x1a, 0x78, 0xad, 0xe3, 0x50, 0xff, 0xaf, 0x68, 0x69, 0xa6, 0x37, 0x50, 0xed, 0x88,
	0x5d, 0x79, 0xf5, 0xf9, 0xc7, 0x3b, 0x73, 0x0e, 0xce, 0xba, 0xeb, 0x19, 0x63, 0xde, 0xa7, 0x2c,
	0x76, 0xbb, 0x7f, 0x1c, 0xe0, 0x57, 0x03, 0x14, 0xbb, 0x2d, 0x1f, 0xbc, 0xd5, 0xbd, 0x75, 0x8f,
	0xcd, 0x2e, 0x2d, 0x9d, 0x84, 0xaa, 0xe7, 0xb8, 0x2b, 0xe7, 0xb8, 0x03, 0x97, 0xfb, 0x99, 0xc3,
	0x57, 0x6a, 0xf3, 0x72, 0x97, 0xe6, 0xf3, 0x1b, 0x5d, 0xdd, 0xd8, 0x3d, 0xb0, 0x8c, 0xbd, 0x03,
	0xcb, 0xf8, 0x7e, 0x60, 0x19, 0x6f, 0x0f, 0xad, 0xc2, 0xde, 0xa1, 0x55, 0xf8, 0x72, 0x68, 0x15,
	0x9e, 0x2c, 0x06, 0x44, 0x34, 0x92, 0x9a, 0xe3, 0xd3, 0xb0, 0x7b, 0x8f, 0xe7, 0xb9, 0x2e, 0xa2,
	0x15, 0x63, 0x5e, 0x1b, 0x96, 0x9f, 0x80, 0xeb, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x75, 0xbb,
	0x84, 0x4f, 0x57, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// CurrentEpochDistribution queries amount of tokens to be distributed in the
	// current epoch.
	CurrentEpochDistribution(ctx context.Context, in *QueryCurrentEpochDistributionRequest, opts ...grpc.CallOption) (*QueryCurrentEpochDistributionResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/galactica.inflation.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CurrentEpochDistribution(ctx context.Context, in *QueryCurrentEpochDistributionRequest, opts ...grpc.CallOption) (*QueryCurrentEpochDistributionResponse, error) {
	out := new(QueryCurrentEpochDistributionResponse)
	err := c.cc.Invoke(ctx, "/galactica.inflation.Query/CurrentEpochDistribution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// CurrentEpochDistribution queries amount of tokens to be distributed in the
	// current epoch.
	CurrentEpochDistribution(context.Context, *QueryCurrentEpochDistributionRequest) (*QueryCurrentEpochDistributionResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) CurrentEpochDistribution(ctx context.Context, req *QueryCurrentEpochDistributionRequest) (*QueryCurrentEpochDistributionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurrentEpochDistribution not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/galactica.inflation.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CurrentEpochDistribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCurrentEpochDistributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CurrentEpochDistribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/galactica.inflation.Query/CurrentEpochDistribution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CurrentEpochDistribution(ctx, req.(*QueryCurrentEpochDistributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "galactica.inflation.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "CurrentEpochDistribution",
			Handler:    _Query_CurrentEpochDistribution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "galactica/inflation/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryCurrentEpochDistributionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCurrentEpochDistributionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCurrentEpochDistributionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryCurrentEpochDistributionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCurrentEpochDistributionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCurrentEpochDistributionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n2, err2 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.EpochDuration, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.EpochDuration):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintQuery(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Distribution.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *CurrentEpochInflationDistribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CurrentEpochInflationDistribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CurrentEpochInflationDistribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OtherShares) > 0 {
		for k := range m.OtherShares {
			v := m.OtherShares[k]
			baseI := i
			{
				size, err := (&v).MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintQuery(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintQuery(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ValidatorsShare.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *CurrentEpochInflationShare) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CurrentEpochInflationShare) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CurrentEpochInflationShare) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Share.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryCurrentEpochDistributionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryCurrentEpochDistributionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Distribution.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.EpochDuration)
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *CurrentEpochInflationDistribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ValidatorsShare.Size()
	n += 1 + l + sovQuery(uint64(l))
	if len(m.OtherShares) > 0 {
		for k, v := range m.OtherShares {
			_ = k
			_ = v
			l = v.Size()
			mapEntrySize := 1 + len(k) + sovQuery(uint64(len(k))) + 1 + l + sovQuery(uint64(l))
			n += mapEntrySize + 1 + sovQuery(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *CurrentEpochInflationShare) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = m.Share.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCurrentEpochDistributionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCurrentEpochDistributionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCurrentEpochDistributionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCurrentEpochDistributionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCurrentEpochDistributionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCurrentEpochDistributionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Distribution", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Distribution.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.EpochDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CurrentEpochInflationDistribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CurrentEpochInflationDistribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CurrentEpochInflationDistribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorsShare", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValidatorsShare.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OtherShares", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OtherShares == nil {
				m.OtherShares = make(map[string]CurrentEpochInflationShare)
			}
			var mapkey string
			mapvalue := &CurrentEpochInflationShare{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowQuery
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowQuery
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthQuery
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthQuery
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowQuery
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthQuery
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthQuery
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &CurrentEpochInflationShare{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipQuery(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthQuery
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.OtherShares[mapkey] = *mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CurrentEpochInflationShare) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CurrentEpochInflationShare: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CurrentEpochInflationShare: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Share", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Share.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
