// Galactica is a Layer 1 protocol with zero-knowledge and privacy features.
// Copyright (C) 2025 Galactica Network
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: galactica/inflation/query.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae5baee6426d48ab, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae5baee6426d48ab, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryCurrentPeriodDistributionRequest is request type for
// Query/CurrentPeriodDistribution RPC method.
type QueryCurrentPeriodDistributionRequest struct {
}

func (m *QueryCurrentPeriodDistributionRequest) Reset()         { *m = QueryCurrentPeriodDistributionRequest{} }
func (m *QueryCurrentPeriodDistributionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCurrentPeriodDistributionRequest) ProtoMessage()    {}
func (*QueryCurrentPeriodDistributionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae5baee6426d48ab, []int{2}
}
func (m *QueryCurrentPeriodDistributionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCurrentPeriodDistributionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCurrentPeriodDistributionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCurrentPeriodDistributionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCurrentPeriodDistributionRequest.Merge(m, src)
}
func (m *QueryCurrentPeriodDistributionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCurrentPeriodDistributionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCurrentPeriodDistributionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCurrentPeriodDistributionRequest proto.InternalMessageInfo

// QueryCurrentPeriodDistributionResponse is response type for
// Query/CurrentPeriodDistribution RPC method.
type QueryCurrentPeriodDistributionResponse struct {
	// amount of coins provisioned to distribute in the current period.
	Amount *types.DecCoin `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// epochs_per_period is the number of epochs in the current period.
	EpochsPerPeriod int64 `protobuf:"varint,2,opt,name=epochs_per_period,json=epochsPerPeriod,proto3" json:"epochs_per_period,omitempty"`
	// epoch_duration is a duration of one epoch.
	EpochDuration time.Duration `protobuf:"bytes,3,opt,name=epoch_duration,json=epochDuration,proto3,stdduration" json:"epoch_duration,omitempty" yaml:"epoch_duration"`
}

func (m *QueryCurrentPeriodDistributionResponse) Reset() {
	*m = QueryCurrentPeriodDistributionResponse{}
}
func (m *QueryCurrentPeriodDistributionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCurrentPeriodDistributionResponse) ProtoMessage()    {}
func (*QueryCurrentPeriodDistributionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae5baee6426d48ab, []int{3}
}
func (m *QueryCurrentPeriodDistributionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCurrentPeriodDistributionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCurrentPeriodDistributionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCurrentPeriodDistributionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCurrentPeriodDistributionResponse.Merge(m, src)
}
func (m *QueryCurrentPeriodDistributionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCurrentPeriodDistributionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCurrentPeriodDistributionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCurrentPeriodDistributionResponse proto.InternalMessageInfo

func (m *QueryCurrentPeriodDistributionResponse) GetAmount() *types.DecCoin {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *QueryCurrentPeriodDistributionResponse) GetEpochsPerPeriod() int64 {
	if m != nil {
		return m.EpochsPerPeriod
	}
	return 0
}

func (m *QueryCurrentPeriodDistributionResponse) GetEpochDuration() time.Duration {
	if m != nil {
		return m.EpochDuration
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "galactica.inflation.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "galactica.inflation.QueryParamsResponse")
	proto.RegisterType((*QueryCurrentPeriodDistributionRequest)(nil), "galactica.inflation.QueryCurrentPeriodDistributionRequest")
	proto.RegisterType((*QueryCurrentPeriodDistributionResponse)(nil), "galactica.inflation.QueryCurrentPeriodDistributionResponse")
}

func init() { proto.RegisterFile("galactica/inflation/query.proto", fileDescriptor_ae5baee6426d48ab) }

var fileDescriptor_ae5baee6426d48ab = []byte{
	// 546 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xcf, 0x6b, 0x13, 0x4f,
	0x14, 0xcf, 0xa6, 0x7c, 0x03, 0xdf, 0x11, 0x95, 0x4e, 0x2b, 0xa4, 0xb1, 0x6c, 0xca, 0x82, 0xb6,
	0x84, 0x66, 0x86, 0x46, 0xbd, 0x54, 0x54, 0x4c, 0x03, 0x3d, 0x1a, 0x03, 0x5e, 0xbc, 0x94, 0xd9,
	0xcd, 0x74, 0x3b, 0x90, 0xdd, 0xb7, 0x9d, 0x9d, 0x15, 0x73, 0x12, 0xbc, 0x7a, 0x50, 0xf0, 0xe2,
	0x9f, 0xe0, 0xd1, 0x3f, 0xa3, 0xc7, 0x82, 0x17, 0x2f, 0x46, 0x49, 0x04, 0xc1, 0xa3, 0x37, 0x6f,
	0xb2, 0x33, 0xb3, 0x25, 0xc1, 0x84, 0x88, 0x87, 0x84, 0xd9, 0x37, 0x9f, 0x1f, 0xef, 0x7d, 0xe6,
	0xa1, 0x7a, 0xc8, 0x06, 0x2c, 0x50, 0x22, 0x60, 0x54, 0xc4, 0xc7, 0x03, 0xa6, 0x04, 0xc4, 0xf4,
	0x34, 0xe3, 0x72, 0x48, 0x12, 0x09, 0x0a, 0xf0, 0xda, 0x05, 0x80, 0x5c, 0x00, 0x6a, 0xab, 0x2c,
	0x12, 0x31, 0x50, 0xfd, 0x6f, 0x70, 0xb5, 0x46, 0x00, 0x69, 0x04, 0x29, 0xf5, 0x59, 0xca, 0x8d,
	0x00, 0x7d, 0xb6, 0xe7, 0x73, 0xc5, 0xf6, 0x68, 0xc2, 0x42, 0x11, 0x6b, 0xa2, 0xc5, 0xba, 0xd3,
	0xd8, 0x02, 0x15, 0x80, 0x28, 0xee, 0xd7, 0x43, 0x08, 0x41, 0x1f, 0x69, 0x7e, 0xb2, 0xd5, 0xcd,
	0x10, 0x20, 0x1c, 0x70, 0xca, 0x12, 0x41, 0x59, 0x1c, 0x83, 0xd2, 0x92, 0x69, 0xa1, 0x69, 0x6f,
	0xf5, 0x97, 0x9f, 0x1d, 0xd3, 0x7e, 0x26, 0xa7, 0x3d, 0xb7, 0xe6, 0x0d, 0x9a, 0x30, 0xc9, 0x22,
	0xab, 0xe0, 0xad, 0x23, 0xfc, 0x38, 0xef, 0xbb, 0xab, 0x8b, 0x3d, 0x7e, 0x9a, 0xf1, 0x54, 0x79,
	0x4f, 0xd0, 0xda, 0x4c, 0x35, 0x4d, 0x20, 0x4e, 0x39, 0xbe, 0x8f, 0x2a, 0x86, 0x5c, 0x75, 0xb6,
	0x9c, 0x9d, 0x4b, 0xad, 0xeb, 0x64, 0x4e, 0x4e, 0xc4, 0x90, 0xda, 0xff, 0x9f, 0x8d, 0xea, 0xa5,
	0xf7, 0xdf, 0x3f, 0x34, 0x9c, 0x9e, 0x65, 0x79, 0xdb, 0xe8, 0x86, 0x96, 0x3d, 0xc8, 0xa4, 0xe4,
	0xb1, 0xea, 0x72, 0x29, 0xa0, 0xdf, 0x11, 0xa9, 0x92, 0xc2, 0xcf, 0x72, 0x6e, 0xe1, 0xff, 0xaa,
	0x8c, 0x6e, 0x2e, 0x43, 0xda, 0x9e, 0x6e, 0xa3, 0x0a, 0x8b, 0x20, 0x8b, 0x95, 0xed, 0x69, 0x93,
	0x98, 0x9c, 0x49, 0x9e, 0x33, 0xb1, 0x39, 0x93, 0x0e, 0x0f, 0x0e, 0x40, 0xc4, 0x3d, 0x8b, 0xc5,
	0x0d, 0xb4, 0xca, 0x13, 0x08, 0x4e, 0xd2, 0xa3, 0x84, 0xcb, 0xfc, 0x27, 0xa0, 0x5f, 0x2d, 0x6f,
	0x39, 0x3b, 0x2b, 0xbd, 0xab, 0xe6, 0xa2, 0xcb, 0xa5, 0x71, 0xc5, 0x2f, 0xd0, 0x15, 0x5d, 0x3a,
	0x2a, 0xc2, 0xad, 0xae, 0x68, 0xa7, 0x0d, 0x62, 0xd2, 0x27, 0x45, 0xfa, 0xa4, 0x63, 0x01, 0xed,
	0x7b, 0xf9, 0xec, 0x3f, 0x46, 0xf5, 0xea, 0x2c, 0x71, 0x17, 0x22, 0xa1, 0x78, 0x94, 0xa8, 0xe1,
	0xcf, 0x51, 0xfd, 0xda, 0x90, 0x45, 0x83, 0x7d, 0x6f, 0x16, 0xe1, 0xbd, 0xfb, 0x52, 0x77, 0x7a,
	0x97, 0x75, 0xb1, 0x50, 0x6b, 0xfd, 0x2a, 0xa3, 0xff, 0x74, 0x1a, 0xf8, 0xb5, 0x83, 0x2a, 0x26,
	0x5e, 0xbc, 0x3d, 0x37, 0xfb, 0x3f, 0xdf, 0xb2, 0xb6, 0xb3, 0x1c, 0x68, 0xa2, 0xf4, 0x5a, 0x2f,
	0x3f, 0x7e, 0x7b, 0x5b, 0xde, 0xc5, 0x0d, 0x7a, 0x58, 0x30, 0x9a, 0x01, 0xc8, 0x84, 0x2e, 0xde,
	0x22, 0xfc, 0xd9, 0x41, 0x1b, 0x0b, 0x1f, 0x09, 0xef, 0x2f, 0xf6, 0x5e, 0xb6, 0x03, 0xb5, 0xbb,
	0xff, 0xc4, 0xb5, 0xa3, 0x1c, 0xea, 0x51, 0x1e, 0xe2, 0x07, 0x7f, 0x33, 0x4a, 0x60, 0xe4, 0x9a,
	0x66, 0x0d, 0x9a, 0xfd, 0x29, 0xc1, 0xf6, 0xa3, 0xb3, 0xb1, 0xeb, 0x9c, 0x8f, 0x5d, 0xe7, 0xeb,
	0xd8, 0x75, 0xde, 0x4c, 0xdc, 0xd2, 0xf9, 0xc4, 0x2d, 0x7d, 0x9a, 0xb8, 0xa5, 0xa7, 0x77, 0x42,
	0xa1, 0x4e, 0x32, 0x9f, 0x04, 0x10, 0x2d, 0x36, 0x79, 0x3e, 0x65, 0xa3, 0x86, 0x09, 0x4f, 0xfd,
	0x8a, 0xde, 0x96, 0x5b, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x04, 0x13, 0xcc, 0x05, 0x84, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// CurrentPeriodDistribution queries amount of tokens to be distributed in the
	// current period.
	CurrentPeriodDistribution(ctx context.Context, in *QueryCurrentPeriodDistributionRequest, opts ...grpc.CallOption) (*QueryCurrentPeriodDistributionResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/galactica.inflation.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CurrentPeriodDistribution(ctx context.Context, in *QueryCurrentPeriodDistributionRequest, opts ...grpc.CallOption) (*QueryCurrentPeriodDistributionResponse, error) {
	out := new(QueryCurrentPeriodDistributionResponse)
	err := c.cc.Invoke(ctx, "/galactica.inflation.Query/CurrentPeriodDistribution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// CurrentPeriodDistribution queries amount of tokens to be distributed in the
	// current period.
	CurrentPeriodDistribution(context.Context, *QueryCurrentPeriodDistributionRequest) (*QueryCurrentPeriodDistributionResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) CurrentPeriodDistribution(ctx context.Context, req *QueryCurrentPeriodDistributionRequest) (*QueryCurrentPeriodDistributionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurrentPeriodDistribution not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/galactica.inflation.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CurrentPeriodDistribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCurrentPeriodDistributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CurrentPeriodDistribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/galactica.inflation.Query/CurrentPeriodDistribution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CurrentPeriodDistribution(ctx, req.(*QueryCurrentPeriodDistributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "galactica.inflation.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "CurrentPeriodDistribution",
			Handler:    _Query_CurrentPeriodDistribution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "galactica/inflation/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryCurrentPeriodDistributionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCurrentPeriodDistributionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCurrentPeriodDistributionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryCurrentPeriodDistributionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCurrentPeriodDistributionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCurrentPeriodDistributionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n2, err2 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.EpochDuration, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.EpochDuration):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintQuery(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x1a
	if m.EpochsPerPeriod != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EpochsPerPeriod))
		i--
		dAtA[i] = 0x10
	}
	if m.Amount != nil {
		{
			size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryCurrentPeriodDistributionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryCurrentPeriodDistributionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Amount != nil {
		l = m.Amount.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.EpochsPerPeriod != 0 {
		n += 1 + sovQuery(uint64(m.EpochsPerPeriod))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.EpochDuration)
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCurrentPeriodDistributionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCurrentPeriodDistributionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCurrentPeriodDistributionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCurrentPeriodDistributionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCurrentPeriodDistributionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCurrentPeriodDistributionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Amount == nil {
				m.Amount = &types.DecCoin{}
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochsPerPeriod", wireType)
			}
			m.EpochsPerPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochsPerPeriod |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.EpochDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
